# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('W', 'weddings'), ('PW', 'pre-weddings')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('top_description', models.TextField()),
                ('bottom_description', models.TextField(blank=True, null=True)),
                ('image_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_one', to='imagesapp.Image')),
                ('image_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_three', to='imagesapp.Image')),
                ('image_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_two', to='imagesapp.Image')),
            ],
        ),
    ]
