# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bottom_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='top_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
