# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20170410_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('weddings', 'weddings'), ('pre-weddings', 'pre-weddings'), ('family', 'family'), ('portrait', 'portrait'), ('personal', 'personal'), ('landscape', 'landscape')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_one', to='imagesapp.Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_three', to='imagesapp.Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_two', to='imagesapp.Image'),
        ),
    ]
