# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20170503_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_one', to='imagesapp.Image'),
            preserve_default=False,
        ),
    ]
