# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20170503_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='top_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image_one',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='bottom_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_two',
        ),
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=models.CharField(default=323, max_length=200),
            preserve_default=False,
        ),
    ]
