# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import imagesapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('W', 'wedding'), ('PW', 'pre-wedding'), ('F', 'family'), ('PO', 'portrait'), ('PE', 'personal')], max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('public', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=imagesapp.models.get_file_path)),
                ('dominantColor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
