# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('W', 'wedding'), ('PW', 'pre-wedding'), ('F', 'family'), ('PO', 'portrait'), ('PE', 'personal'), ('LS', 'landscape')], max_length=15),
        ),
    ]
