# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import personalapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about_image', models.BooleanField(default=False)),
                ('landing_image', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=personalapp.models.get_file_path)),
            ],
        ),
    ]
